###to test. install rest-client extension

###signup 
POST  http://127.0.0.1:8000/api/v1/signup
Accept: application/json
Content-Type: application/json

{
    "name": "test",
    "username": "mathtutor939",
    "phone_number": "012323279",
    "account_type": "service_provider",
    "password": "Lyhour99"
}

###login with number (only works with cambodian dialog code +855)
### 'SMS Info'as sender name cuz free trial
POST  http://127.0.0.1:8000/api/v1/number-signin
Accept: application/json
Content-Type: application/json

{
    "phone_number": "078870993"
}

###verify otp code
POST  http://127.0.0.1:8000/api/v1/verify-otp
Accept: application/json
Content-Type: application/json

{
    "user_id": "4",
    "code": "19983"
}

###username/phone-number and password login
POST  http://127.0.0.1:8000/api/v1/login
Accept: application/json
Content-Type: application/json

{
    "username": "test1234",
    "password": "Lyhour99"
}

###adding service as a service provider
POST  http://127.0.0.1:8000/api/v1/add-service
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJTZXJ2aWNlIEh1YiIsImlhdCI6MTcwNjIxODc0MCwiZXhwIjoxNzM3Nzc2MzQwLCJuYmYiOjE3MDYyMTg3NDAsImp0aSI6IndkRFlrdXR4QVh3T3VSR2wiLCJzdWIiOiIxIiwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyIsImRhdGEiOnsiaWQiOjEsIm5hbWUiOiJ0ZXN0IiwiZW1haWwiOm51bGwsInBob25lX251bWJlciI6IjAxMjU0MTU3OSIsInNvY2lhbF9tZWRpYV9pZCI6bnVsbCwiYWNjb3VudF90eXBlIjoic2VydmljZV9wcm92aWRlciIsImNyZWF0ZWRfYXQiOiIyMDI0LTAxLTI0VDAxOjEzOjI1LjAwMDAwMFoiLCJ1cGRhdGVkX2F0IjoiMjAyNC0wMS0yNFQwMToxMzoyNS4wMDAwMDBaIiwidXNlcm5hbWUiOiJ0ZXN0MTIzIiwidmVyaWZpZWQiOjB9fQ.rvu5HnI4M5laMtZlXwbyONJqS50jSb445c6murBOaig

{
    "service_name":  "babysitting",
    "service_description": "test",
    "service_category": "Childcare and Babysitting",
    "pricing": "12.2"
}

###Service List
GET  http://127.0.0.1:8000/api/v1/service-list
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJTZXJ2aWNlIEh1YiIsImlhdCI6MTcwNjIxODc0MCwiZXhwIjoxNzM3Nzc2MzQwLCJuYmYiOjE3MDYyMTg3NDAsImp0aSI6IndkRFlrdXR4QVh3T3VSR2wiLCJzdWIiOiIxIiwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyIsImRhdGEiOnsiaWQiOjEsIm5hbWUiOiJ0ZXN0IiwiZW1haWwiOm51bGwsInBob25lX251bWJlciI6IjAxMjU0MTU3OSIsInNvY2lhbF9tZWRpYV9pZCI6bnVsbCwiYWNjb3VudF90eXBlIjoic2VydmljZV9wcm92aWRlciIsImNyZWF0ZWRfYXQiOiIyMDI0LTAxLTI0VDAxOjEzOjI1LjAwMDAwMFoiLCJ1cGRhdGVkX2F0IjoiMjAyNC0wMS0yNFQwMToxMzoyNS4wMDAwMDBaIiwidXNlcm5hbWUiOiJ0ZXN0MTIzIiwidmVyaWZpZWQiOjB9fQ.rvu5HnI4M5laMtZlXwbyONJqS50jSb445c6murBOaig

###Edit service
PATCH http://127.0.0.1:8000/api/v1/edit-service/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJTZXJ2aWNlIEh1YiIsImlhdCI6MTcwNjIxODc0MCwiZXhwIjoxNzM3Nzc2MzQwLCJuYmYiOjE3MDYyMTg3NDAsImp0aSI6IndkRFlrdXR4QVh3T3VSR2wiLCJzdWIiOiIxIiwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyIsImRhdGEiOnsiaWQiOjEsIm5hbWUiOiJ0ZXN0IiwiZW1haWwiOm51bGwsInBob25lX251bWJlciI6IjAxMjU0MTU3OSIsInNvY2lhbF9tZWRpYV9pZCI6bnVsbCwiYWNjb3VudF90eXBlIjoic2VydmljZV9wcm92aWRlciIsImNyZWF0ZWRfYXQiOiIyMDI0LTAxLTI0VDAxOjEzOjI1LjAwMDAwMFoiLCJ1cGRhdGVkX2F0IjoiMjAyNC0wMS0yNFQwMToxMzoyNS4wMDAwMDBaIiwidXNlcm5hbWUiOiJ0ZXN0MTIzIiwidmVyaWZpZWQiOjB9fQ.rvu5HnI4M5laMtZlXwbyONJqS50jSb445c6murBOaig

{
    "service_description": "new description 2"
}

###remove service
DELETE http://127.0.0.1:8000/api/v1/remove-service/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJTZXJ2aWNlIEh1YiIsImlhdCI6MTcwNjIxODc0MCwiZXhwIjoxNzM3Nzc2MzQwLCJuYmYiOjE3MDYyMTg3NDAsImp0aSI6IndkRFlrdXR4QVh3T3VSR2wiLCJzdWIiOiIxIiwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyIsImRhdGEiOnsiaWQiOjEsIm5hbWUiOiJ0ZXN0IiwiZW1haWwiOm51bGwsInBob25lX251bWJlciI6IjAxMjU0MTU3OSIsInNvY2lhbF9tZWRpYV9pZCI6bnVsbCwiYWNjb3VudF90eXBlIjoic2VydmljZV9wcm92aWRlciIsImNyZWF0ZWRfYXQiOiIyMDI0LTAxLTI0VDAxOjEzOjI1LjAwMDAwMFoiLCJ1cGRhdGVkX2F0IjoiMjAyNC0wMS0yNFQwMToxMzoyNS4wMDAwMDBaIiwidXNlcm5hbWUiOiJ0ZXN0MTIzIiwidmVyaWZpZWQiOjB9fQ.rvu5HnI4M5laMtZlXwbyONJqS50jSb445c6murBOaig

###Booking list
GET  http://127.0.0.1:8000/api/v1/booking-list
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJTZXJ2aWNlIEh1YiIsImlhdCI6MTcwNjIzNjY2MywiZXhwIjoxNzM3Nzk0MjYzLCJuYmYiOjE3MDYyMzY2NjMsImp0aSI6Img2MVphMGVmZURwcG14UG4iLCJzdWIiOiI0IiwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyIsImRhdGEiOnsiaWQiOjQsIm5hbWUiOiJ0ZXN0IiwiZW1haWwiOm51bGwsInBob25lX251bWJlciI6IjA3ODg3MDk5MyIsInNvY2lhbF9tZWRpYV9pZCI6bnVsbCwiYWNjb3VudF90eXBlIjoiY2xpZW50IiwiY3JlYXRlZF9hdCI6IjIwMjQtMDEtMjRUMDE6NDY6NDYuMDAwMDAwWiIsInVwZGF0ZWRfYXQiOiIyMDI0LTAxLTI0VDAxOjQ2OjQ2LjAwMDAwMFoiLCJ1c2VybmFtZSI6InRlc3QxMjM0IiwidmVyaWZpZWQiOjB9fQ.0yNWQk-Gu2uYsMbBds5-irkzcJ8ejC-fLCmRLWlqVZ0

###book a service
POST  http://127.0.0.1:8000/api/v1/booking/2
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJTZXJ2aWNlIEh1YiIsImlhdCI6MTcwNjIzNjY2MywiZXhwIjoxNzM3Nzk0MjYzLCJuYmYiOjE3MDYyMzY2NjMsImp0aSI6Img2MVphMGVmZURwcG14UG4iLCJzdWIiOiI0IiwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyIsImRhdGEiOnsiaWQiOjQsIm5hbWUiOiJ0ZXN0IiwiZW1haWwiOm51bGwsInBob25lX251bWJlciI6IjA3ODg3MDk5MyIsInNvY2lhbF9tZWRpYV9pZCI6bnVsbCwiYWNjb3VudF90eXBlIjoiY2xpZW50IiwiY3JlYXRlZF9hdCI6IjIwMjQtMDEtMjRUMDE6NDY6NDYuMDAwMDAwWiIsInVwZGF0ZWRfYXQiOiIyMDI0LTAxLTI0VDAxOjQ2OjQ2LjAwMDAwMFoiLCJ1c2VybmFtZSI6InRlc3QxMjM0IiwidmVyaWZpZWQiOjB9fQ.0yNWQk-Gu2uYsMbBds5-irkzcJ8ejC-fLCmRLWlqVZ0

{

}

###cancel booking
DELETE   http://127.0.0.1:8000/api/v1/booking/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJTZXJ2aWNlIEh1YiIsImlhdCI6MTcwNjIzNjY2MywiZXhwIjoxNzM3Nzk0MjYzLCJuYmYiOjE3MDYyMzY2NjMsImp0aSI6Img2MVphMGVmZURwcG14UG4iLCJzdWIiOiI0IiwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyIsImRhdGEiOnsiaWQiOjQsIm5hbWUiOiJ0ZXN0IiwiZW1haWwiOm51bGwsInBob25lX251bWJlciI6IjA3ODg3MDk5MyIsInNvY2lhbF9tZWRpYV9pZCI6bnVsbCwiYWNjb3VudF90eXBlIjoiY2xpZW50IiwiY3JlYXRlZF9hdCI6IjIwMjQtMDEtMjRUMDE6NDY6NDYuMDAwMDAwWiIsInVwZGF0ZWRfYXQiOiIyMDI0LTAxLTI0VDAxOjQ2OjQ2LjAwMDAwMFoiLCJ1c2VybmFtZSI6InRlc3QxMjM0IiwidmVyaWZpZWQiOjB9fQ.0yNWQk-Gu2uYsMbBds5-irkzcJ8ejC-fLCmRLWlqVZ0




###submit review
POST http://127.0.0.1:8000/api/v1/submit-review/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJTZXJ2aWNlIEh1YiIsImlhdCI6MTcwNjIzNjY2MywiZXhwIjoxNzM3Nzk0MjYzLCJuYmYiOjE3MDYyMzY2NjMsImp0aSI6Img2MVphMGVmZURwcG14UG4iLCJzdWIiOiI0IiwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyIsImRhdGEiOnsiaWQiOjQsIm5hbWUiOiJ0ZXN0IiwiZW1haWwiOm51bGwsInBob25lX251bWJlciI6IjA3ODg3MDk5MyIsInNvY2lhbF9tZWRpYV9pZCI6bnVsbCwiYWNjb3VudF90eXBlIjoiY2xpZW50IiwiY3JlYXRlZF9hdCI6IjIwMjQtMDEtMjRUMDE6NDY6NDYuMDAwMDAwWiIsInVwZGF0ZWRfYXQiOiIyMDI0LTAxLTI0VDAxOjQ2OjQ2LjAwMDAwMFoiLCJ1c2VybmFtZSI6InRlc3QxMjM0IiwidmVyaWZpZWQiOjB9fQ.0yNWQk-Gu2uYsMbBds5-irkzcJ8ejC-fLCmRLWlqVZ0

{
    "rating": 4
}